Repository dForDeveloper/paired-api, pull requests merged in 2019-04, with the labels that each got.

#1 Create schema and test endpoint
  app.js
  schema.js
  server.js
Labels: in progress

#2 Seed DB with user info
  db/schema.js
  package-lock.json
  schema.js
  seed/seeds.js
  server.js
Labels: in progress

#6 Set up GraphQL
  apollo/resolvers.js
  apollo/schema.js
  app.js
  db/schema.js
  package-lock.json
  package.json
  schema.js
  seed/seeds.js
  server.js
Labels: backend, in progress

#8 Fix getAvailablePairings query, resolve #7
  README.md
  apollo/resolvers.js
  apollo/typeDefs.js
  db/schema.js
  db/seeds.js
  server.js
Labels: graphql, in progress

#10 Test getUser and getUsers resolvers
  apollo/resolvers.test.js
  db/seeds.js
  package.json
Labels: in progress

#12 Created test for attributes of input calls in apollo schema
  apollo/typeDefs.test.js
  package-lock.json
  package.json
Labels: in progress

#13 Test getPairings query and createUser and createPairing mutation
  apollo/resolvers.test.js
Labels: in progress

#15 Add and test mutations for updateUser and updatePairing
  apollo/resolvers.js
  apollo/resolvers.test.js
  apollo/typeDefs.js
  apollo/typeDefs.test.js
  db/seedScript.js
  db/seeds.js
  package.json
Labels: in progress

#17 Add and test deleteUser and deletePairing mutations
  README.md
  apollo/resolvers.js
  apollo/resolvers.test.js
  apollo/typeDefs.js
Labels: in progress

#18 Add more seed pairings for front end development
  apollo/resolvers.test.js
  db/seeds.js
Labels: in progress

#19 Add createPairings mutation
  README.md
  apollo/resolvers.js
  apollo/resolvers.test.js
  apollo/typeDefs.js
Labels: in progress
